### ISSUE TITLE
rocks-dev can't install local version of plugin that other plugins depend on

### ISSUE THREAD

**Issue by benlubas** [nvim-neorocks/rocks-dev.nvim#31]
I want to have `neorg` installed via rocks-dev, and `neorg-se` installed normally from luarocks, but `neorg-se` depends on `neorg`, so when I list `neorg = { dev = true }` the plugin tries and fails to uninstall `neorg`. And the local version of `neorg` is not loaded.

log after running `:Rocks sync` with dev `neorg` and luarocks versions of a few neorg modules:
```
[START][2024-07-29 13:48:55] rocks.nvim logging initiated
ERROR | 2024-07-29 13:49:02 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:65 | luarocks CLI FAILED
ERROR | 2024-07-29 13:49:02 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:66 | Will not remove neorg 9.1.1-1.
Removing it would break dependencies for: 
neorg-interim-ls 1.2.0-1
neorg-telescope 1.2.2-1
neorg-se 1.1.10-1
neorg-conceal-wrap 1.0.0-1

Use --force to force removal (warning: this may break modules).

Error: Failed removing.

ERROR | 2024-07-29 13:49:02 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/sync.lua:48 | SYNC ERROR: rocks-dev: Failed to remove neorg
ERROR | 2024-07-29 13:49:11 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/sync.lua:267 | Sync completed with errors! Run ':Rocks log' for details.
```

Few questions I guess:
- Is this currently possible, would I have to install dev/git versions of all of my neorg modules? 
- rocks-dev doesn't support local rock specs, right? So I'd have to install neorg's dependencies myself if I want the dev plugin to work?

**Comment by mrcjkb** [comment]
Hey 👋 

That's currently not possible, but it's [on the horizon](https://github.com/nvim-neorocks/rocks.nvim/issues/365).

So many construction sites 😅

**Comment by mrcjkb** [comment]
should be fixed with the new experimental feature. See https://github.com/nvim-neorocks/rocks.nvim/discussions/530
