### ISSUE TITLE
rocks-confing configurations not loaded

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks-dev.nvim#8]
### Problem

rocks-config, when loaded using rocks-dev, cannot load any plugins, because it is added to the rtp too late.

### Solution

Use a packpath, and symlink the `dev` paths during initialisation (and during sync).

```lua
vim.fs.joinpath(vim.fn.stdpath("data"), "site", "pack", "rocks-dev"),
```

Bonus: This would also allow rocks-dev to support the `opt` flag, by putting symlinks in the `start` or `opt` directory.

**Comment by sahinf** [comment]
Hey any updates on a PR to fix #15?

**Comment by mrcjkb** [comment]
> Hey any updates on a PR to fix #15?

This is still on my radar, but it isn't on the top of my stack of things to do right now 😞 

But PRs are more than welcome 😃
Related: https://github.com/nvim-neorocks/rocks.nvim/pull/285

**Comment by sahinf** [comment]
I'm still having the same issue though. 

rocks.toml
```toml
[plugins]
# neorg = "8.7.1"
"rocks-dev.nvim" = "1.2.3"

[plugins.'neorg']
dir = "~/projects/neorg"
```

init.lua
```lua
vim.cmd.packadd { 'rocks-dev.nvim', bang = true }
```

run `:Rocks sync`, then run new `nvim`
```sh
Warning [neorg]: lua-utils not found. If you're just installing the plugin, ignore this message, when in doubt run `:Lazy build neorg`. If you're not on lazy please rerun the build scripts.
```

and I verified that Rocks didn't import the local copy through `find ~/.local/share/ -type d -name '*neorg*' -prune`.

I'm not sure how to debug this further. Any suggestions?

**Comment by mrcjkb** [comment]
> I'm not sure how to debug this further. Any suggestions?

So your previous workaround (`packadd` without `bang = true`) no longer works?

Is lua-utils.nvim installed? rocks-dev doesn't install plugin dependencies.
If it is, you could also try adding

```lua
vim.cmd.packadd { 'lua-utils.nvim', bang = true }
```

**Comment by mrcjkb** [comment]
Another idea: Now that rocks-config has a `configure` API, we could use that.

Edit: Although, this would not work with bundles :disappointed:
